# Use the official Node.js image as a base
FROM node:14-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code to the working directory
COPY . .

# Build the Vite app
RUN npm run build

# Stage 2: Use the official Nginx image as a base
FROM nginx:alpine

# Copy the built Vite app from the previous stage to the Nginx HTML directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to start Nginx and keep it running in the foreground
CMD ["nginx", "-g", "daemon off;"]
