# Use a base image with Node.js pre-installed
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory and its just a sample
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Run the build command
RUN npm run build

# Expose any ports the app is expecting
EXPOSE 3000

# Command to run the application
CMD [ "npm", "start" ]
